/* Commerce-Students feature pack: archive, search and quiz. */
(function () {
  'use strict';
  var W = window, D = document, app = D.getElementById('app');
  if (!app) return;
  var CS = W.CS || {}, SUBJECTS = CS.SUBJECTS || ['accountancy','business','economics','english','information'];
  var NAMES = CS.SUBJECT_NAMES || {}, QUIZ_KEY = 'cs-quiz-state', SCORE_KEY = 'cs-quiz-scores';
  var quizTimer = null, quiz = null;
  var papers = [
    { year: '2025', grade: 'Class 12', subject: 'All commerce subjects', url: 'https://www.cbse.gov.in/cbsenew/question-paper.html', note: 'CBSE question-paper archive' },
    { year: '2024', grade: 'Class 12', subject: 'Accountancy', url: 'https://www.cbse.gov.in/cbsenew/question-paper.html', note: 'Verify the subject PDF on CBSE' },
    { year: '2024', grade: 'Class 12', subject: 'Business Studies', url: 'https://www.cbse.gov.in/cbsenew/question-paper.html', note: 'Verify the subject PDF on CBSE' },
    { year: '2024', grade: 'Class 12', subject: 'Economics', url: 'https://www.cbse.gov.in/cbsenew/question-paper.html', note: 'Verify the subject PDF on CBSE' },
    { year: '2024', grade: 'Class 11', subject: 'Commerce subjects', url: 'https://cbseacademic.nic.in/', note: 'CBSE Academic resources' }
  ];
  function esc(v) { return String(v).replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]; }); }
  function json(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || 'null') || fallback; } catch (e) { return fallback; } }
  function put(key, val) { try { localStorage.setItem(key, JSON.stringify(val)); } catch (e) {} }
  function chapters() { var out = []; [11,12].forEach(function (g) { SUBJECTS.forEach(function (s) { var b = CS.bank && CS.bank(g,s); if (!b) return; b.chapters.forEach(function (c,i) { out.push({grade:g,subject:s,index:i,title:c.t}); }); }); }); return out; }
  function nav() { var n = D.querySelector('.main-nav'); if (!n || n.querySelector('[data-feature-nav]')) return; n.insertAdjacentHTML('beforeend', '<a class="nav-link" data-feature-nav data-nav="search" href="#search">Search</a><a class="nav-link" data-feature-nav data-nav="papers" href="#papers">Papers</a><a class="nav-link" data-feature-nav data-nav="quiz" href="#quiz">Quiz</a>'); }
  function css() { if (D.getElementById('feature-css')) return; var s=D.createElement('style'); s.id='feature-css'; s.textContent='.feature-stat-grid,.feature-card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:22px 0}.feature-stat,.feature-panel,.feature-card,.quiz-box{padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--card)}.feature-stat strong{display:block;font-size:34px}.feature-stat span,.feature-muted,.feature-card small{color:var(--muted);font-size:12px}.feature-search{width:100%;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--bg);margin:22px 0}.feature-results{display:grid;gap:8px}.feature-result{display:flex;justify-content:space-between;gap:12px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--card)}.paper-links,.quiz-box{display:grid;gap:12px}.feature-card h3{margin-bottom:6px}.quiz-options{display:grid;gap:9px;margin:18px 0}.quiz-options label{padding:12px;border:1px solid var(--line);border-radius:10px}.quiz-meta{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px;font-weight:700}.quiz-timer{font-size:24px}.feature-card-grid{grid-template-columns:repeat(3,1fr)}.feature-logo{width:72px;height:72px;border-radius:24px;object-fit:cover;border:1px solid var(--line)}@media(max-width:700px){.feature-stat-grid,.feature-card-grid{grid-template-columns:1fr}}'; D.head.appendChild(s); }
  function shell(kicker,title,intro,body) { app.innerHTML='<section class="shell page-view"><div class="eyebrow">'+kicker+'</div><h1 class="page-title">'+title+'</h1><p class="page-intro">'+intro+'</p>'+body+'</section>'; }
  function search() { var all=chapters(); shell('Find a topic','Search chapters','Search by chapter, subject or class.','<label class="sr-only" for="feature-search">Search chapters</label><input class="feature-search" id="feature-search" type="search" placeholder="Try national income, Class 12 or economics" autocomplete="off"><div class="feature-results" id="feature-results"></div>'); var input=D.getElementById('feature-search'),box=D.getElementById('feature-results'); function paint(){var q=input.value.toLowerCase().trim(),f=all.filter(function(x){return !q||(x.title+' '+x.subject+' class '+x.grade).toLowerCase().indexOf(q)!==-1;}).slice(0,100); box.innerHTML=f.length?f.map(function(x){return '<a class="feature-result" href="#class-'+x.grade+'/'+x.subject+'"><strong>'+esc(x.title)+'</strong><small>Class '+x.grade+' · '+esc(NAMES[x.subject]||x.subject)+'</small></a>';}).join(''):'<p class="feature-muted">No matching chapters.</p>'; announce(f.length+' search results.');} input.addEventListener('input',paint);paint(); }
  function archive() { shell('Practice archive','Previous-year papers','Browse paper cards by year, class and subject. Replace a card URL with your verified PDF when available.','<div class="feature-card-grid">'+papers.map(function(p){return '<article class="feature-card"><div class="eyebrow">'+esc(p.year)+' · '+esc(p.grade)+'</div><h3>'+esc(p.subject)+'</h3><small>'+esc(p.note)+'</small><p><a class="btn btn-soft btn-sm" target="_blank" rel="noreferrer" href="'+p.url+'">Open paper ↗</a></p></article>';}).join('')+'</div>'); }
  function quizQuestions(){var b=CS.bank&&CS.bank(11,'accountancy'),out=[]; if(!b)return out; b.chapters.forEach(function(c,ci){(c.mcq||[]).forEach(function(q,qi){out.push({q:q[0],opts:q[1],correct:q[2],exp:q[3],id:'11-accountancy-'+ci+'-'+qi});});}); return out.slice(0,10);}
  function saveQuiz(){if(quiz)put(QUIZ_KEY,quiz);}
  function formatTime(s){return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
  function stopTimer(){if(quizTimer){clearInterval(quizTimer);quizTimer=null;}}
  function quizPage(){var saved=json(QUIZ_KEY,null); quiz=saved&&saved.questions? saved : {questions:quizQuestions(),at:0,answers:{},seconds:300,paused:false,finished:false}; if(!quiz.questions.length){shell('Timed practice','Quiz unavailable','No MCQs are available for this quiz yet.','');return;} renderQuiz();}
  function renderQuiz(){stopTimer(); var q=quiz.questions[quiz.at], selected=quiz.answers[quiz.at]; shell('Timed practice','Five-minute MCQ quiz','Answer with the mouse, keyboard, or screen reader. Your current quiz is saved locally.','<div class="quiz-box" role="region" aria-labelledby="quiz-question"><div class="quiz-meta"><span>Question '+(quiz.at+1)+' of '+quiz.questions.length+'</span><span class="quiz-timer" id="quiz-timer" aria-live="polite">'+formatTime(quiz.seconds)+'</span></div><h2 id="quiz-question" tabindex="-1">'+esc(q.q)+'</h2><div class="quiz-options" role="radiogroup" aria-label="Answer options">'+q.opts.map(function(o,i){return '<label><input type="radio" name="quiz-option" value="'+i+'" '+(selected===i?'checked':'')+'> '+('ABCD'[i])+'. '+esc(o)+'</label>';}).join('')+'</div><div class="rev-actions"><button class="btn btn-solid" id="quiz-next" type="button">'+(quiz.at===quiz.questions.length-1?'Finish quiz':'Next question')+' →</button><button class="btn btn-soft" id="quiz-pause" type="button">'+(quiz.paused?'Resume':'Pause')+'</button><button class="btn btn-soft" id="quiz-reset" type="button">Restart</button></div><p class="feature-muted" id="quiz-status" aria-live="polite">'+(quiz.paused?'Paused. Press Resume or P to continue.':'Press 1–4 to choose an answer, Enter for next, or P to pause.')+'</p></div>'); var heading=D.getElementById('quiz-question'); if(heading)heading.focus(); if(!quiz.paused&&!quiz.finished){quizTimer=setInterval(function(){quiz.seconds--;if(quiz.seconds<=0){quiz.seconds=0;quiz.finished=true;saveQuiz();stopTimer();finishQuiz();return;}var t=D.getElementById('quiz-timer');if(t)t.textContent=formatTime(quiz.seconds);saveQuiz();},1000);} }
  function finishQuiz(){stopTimer();var score=quiz.questions.reduce(function(n,q,i){return n+(quiz.answers[i]===q.correct?1:0);},0);var scores=json(SCORE_KEY,[]);scores.unshift({date:new Date().toLocaleString(),score:score,total:quiz.questions.length});put(SCORE_KEY,scores.slice(0,20));shell('Quiz complete','Your quiz result','Scores are saved privately in this browser.','<div class="feature-stat-grid"><div class="feature-stat"><strong>'+score+'/'+quiz.questions.length+'</strong><span>correct</span></div><div class="feature-stat"><strong>'+Math.round(score/quiz.questions.length*100)+'%</strong><span>score</span></div><div class="feature-stat"><strong>'+formatTime(300-quiz.seconds)+'</strong><span>time used</span></div></div><p><button class="btn btn-solid" id="quiz-again" type="button">Try again</button> <a class="btn btn-soft" href="#search">Search chapters</a></p><div class="feature-panel"><h2>Saved scores</h2>'+scores.slice(0,5).map(function(x){return '<p>'+esc(x.date)+' · <b>'+x.score+'/'+x.total+'</b></p>';}).join('')+'</div>'); announce('Quiz complete. You scored '+score+' out of '+quiz.questions.length+'.'); D.getElementById('quiz-again').onclick=function(){localStorage.removeItem(QUIZ_KEY);quiz=null;quizPage();};}
  function announce(text){var live=D.getElementById('feature-live');if(!live){live=D.createElement('div');live.id='feature-live';live.className='sr-only';live.setAttribute('aria-live','polite');D.body.appendChild(live);}live.textContent=text;}
  function route(){nav();css();var r=location.hash.slice(1);if(r==='search')search();else if(r==='papers')archive();else if(r==='quiz')quizPage();}
  app.addEventListener('click',function(e){if(e.target.id==='quiz-next'){var pick=D.querySelector('input[name="quiz-option"]:checked');if(pick)quiz.answers[quiz.at]=Number(pick.value);if(quiz.at===quiz.questions.length-1){quiz.finished=true;saveQuiz();finishQuiz();}else{quiz.at++;saveQuiz();renderQuiz();}}if(e.target.id==='quiz-pause'){quiz.paused=!quiz.paused;saveQuiz();renderQuiz();}if(e.target.id==='quiz-reset'){localStorage.removeItem(QUIZ_KEY);quiz=null;quizPage();}});
  D.addEventListener('keydown',function(e){if(location.hash!=='#quiz'||!quiz||quiz.finished)return;if(['INPUT','SELECT','TEXTAREA'].indexOf(D.activeElement.tagName)!==-1&&e.key!=='Enter')return;if(['1','2','3','4'].indexOf(e.key)!==-1){var x=D.querySelectorAll('input[name="quiz-option"]')[Number(e.key)-1];if(x){x.checked=true;x.focus();announce('Option '+e.key+' selected.');}}if(e.key.toLowerCase()==='p'){quiz.paused=!quiz.paused;saveQuiz();renderQuiz();}if(e.key==='Enter'&&D.activeElement.tagName!=='BUTTON'){var b=D.getElementById('quiz-next');if(b)b.click();}});
  W.addEventListener('hashchange',route); route();
})();
